import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { EXECUTION_STAGES, initializeWorkspace, promoteStage, reopenStage, resumeWorkspace, verifyWorkspace, recoverWriterLock } from "../skills/figthread/runtime/execution.js";

async function fresh(){const root=await mkdtemp(join(tmpdir(),"figthread-exec-")),source=join(root,"source.txt");await writeFile(source,"source-bytes","utf8");const init=await initializeWorkspace(join(root,"runs"),source,{runId:"run-test"});return{root,source,run:init.run_dir,init};}
async function promoteFrontier(run,label="artifact"){const packet=await resumeWorkspace(run);assert.equal(packet.status,"ready");const artifact=join(run,packet.revision_dir,`${label}.txt`),evidence=join(run,"evidence",`${packet.frontier_stage}-${packet.revision}.txt`);await writeFile(artifact,`${label}:${packet.frontier_stage}:${packet.revision}`,"utf8");await writeFile(evidence,`review:${packet.frontier_stage}:${packet.revision}`,"utf8");return promoteStage(run,packet.frontier_stage,{artifacts:[artifact],evidence:[evidence]});}

test("workspace initializes a self-contained resumable frontier",async()=>{const {run,init}=await fresh();assert.equal(init.frontier_stage,"understanding");const packet=await resumeWorkspace(run);assert.equal(packet.status,"ready");assert.equal(packet.frontier_stage,"understanding");assert.equal(packet.revision_dir,"stages/01-understanding/r0001");const verification=await verifyWorkspace(run);assert.equal(verification.valid,true);});

test("promotion binds exact artifact/evidence bytes and advances checkpointed frontier",async()=>{const {run}=await fresh(),result=await promoteFrontier(run);assert.equal(result.promoted,true);assert.equal(result.stage_id,"understanding");assert.equal(result.frontier_stage,"claims");assert.match(result.receipt.receipt_hash,/^sha256:[0-9a-f]{64}$/);assert.equal(result.receipt.artifacts.length,1);assert.equal(result.receipt.evidence.length,1);assert.match(result.checkpoint_hash,/^sha256:/);const receipt=JSON.parse(await readFile(join(run,result.receipt_path),"utf8"));assert.equal(receipt.receipt_hash,result.receipt.receipt_hash);});

test("path existence alone cannot skip the active frontier",async()=>{const {run}=await fresh(),packet=await resumeWorkspace(run),artifact=join(run,packet.revision_dir,"a.txt"),evidence=join(run,"evidence","a.txt");await writeFile(artifact,"a");await writeFile(evidence,"e");await assert.rejects(()=>promoteStage(run,"claims",{artifacts:[artifact],evidence:[evidence]}),error=>error.code==="EXE006_FRONTIER");});

test("tampered promoted bytes locate the earliest invalid stage and reopen can recover it",async()=>{const {run}=await fresh();await promoteFrontier(run,"u");const claims=await promoteFrontier(run,"c");await promoteFrontier(run,"f");await writeFile(join(run,claims.receipt.artifacts[0].path),"changed","utf8");const bad=await verifyWorkspace(run);assert.equal(bad.valid,false);assert.equal(bad.reopen_required_stage,"claims");const packet=await resumeWorkspace(run);assert.equal(packet.status,"reopen-required");assert.equal(packet.reopen_required_stage,"claims");const reopened=await reopenStage(run,"claims","review found changed promoted bytes");assert.equal(reopened.revision,2);assert.deepEqual(reopened.invalidated.map(x=>x.stage_id),["claims","figure-ir"]);assert.equal((await resumeWorkspace(run)).revision_dir,"stages/02-claims/r0002");assert.equal((await verifyWorkspace(run)).valid,true);});

test("reopen preserves immutable history while invalidating all descendants",async()=>{const {run}=await fresh();const receipts=[];for(let i=0;i<4;i++)receipts.push(await promoteFrontier(run,`s${i}`));const oldPath=receipts[2].receipt_path,oldBytes=await readFile(join(run,oldPath),"utf8");const reopened=await reopenStage(run,"figure-ir","hierarchy review exposed semantic cause");assert.equal(reopened.revision,2);assert.deepEqual(reopened.invalidated.map(x=>x.stage_id),["figure-ir","grammar-visual"]);assert.equal(await readFile(join(run,oldPath),"utf8"),oldBytes);const packet=await resumeWorkspace(run);assert.equal(packet.frontier_stage,"figure-ir");});

test("fresh worker can finish the entire run from resume packets only",async()=>{const {run}=await fresh();for(const expected of EXECUTION_STAGES){const packet=await resumeWorkspace(run);assert.equal(packet.frontier_stage,expected.id);await promoteFrontier(run,expected.id);}const packet=await resumeWorkspace(run);assert.equal(packet.status,"complete");assert.equal((await verifyWorkspace(run)).complete,true);});

test("intake provenance damage is fatal rather than silently reopened",async()=>{const {run}=await fresh();await writeFile(join(run,"intake","source.txt"),"different","utf8");const verification=await verifyWorkspace(run);assert.equal(verification.valid,false);assert.ok(verification.issues.some(x=>x.code==="EXE002_SOURCE"));await assert.rejects(()=>reopenStage(run,"understanding","try to hide source change"),error=>error.code==="EXE002_SOURCE");});

test("stale writer lock requires explicit audited recovery",async()=>{const {run}=await fresh();await writeFile(join(run,".figthread-writer.lock"),JSON.stringify({pid:999999,operation:"crashed"}),"utf8");await assert.rejects(()=>promoteFrontier(run),error=>error.code==="EXE007_LOCK");const recovered=await recoverWriterLock(run,"confirmed crashed worker");assert.equal(recovered.recovered,true);assert.match(recovered.recovery_hash,/^sha256:/);assert.equal((await verifyWorkspace(run)).valid,true);});

test("execution schema root mirrors match installed skill",async()=>{for(const name of ["run-manifest.schema.json","stage-receipt.schema.json","checkpoint.schema.json"]){const [a,b]=await Promise.all([readFile(new URL(`../skills/figthread/schemas/${name}`,import.meta.url),"utf8"),readFile(new URL(`../schemas/${name}`,import.meta.url),"utf8")]);assert.equal(a,b);}});
