import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { promoteFigureSpec } from "../skills/figthread/runtime/validator.js";
import { compilePromotedLayout, promoteResolvedLayout } from "../skills/figthread/runtime/layout.js";

const figure = JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.figure.json", import.meta.url), "utf8"));
const request = JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.layout-request.json", import.meta.url), "utf8"));
const promote = (doc = figure) => { const result = promoteFigureSpec(doc); assert.equal(result.promoted, true); return result; };
const has = (report, code, objectId) => report.issues.some((entry) => entry.code === code && (objectId === undefined || entry.object_id === objectId));

test("D-002 consumes the D-001 promoted FigureSpec and produces stable geometry", () => { const promotion=promote(),a=compilePromotedLayout(promotion,request),b=compilePromotedLayout(promotion,request); assert.equal(a.status,"pass"); assert.equal(a.promotion_eligible,true); assert.equal(a.layout_hash,b.layout_hash); assert.deepEqual(a.resolved_layout,b.resolved_layout); assert.equal(a.resolved_layout.boxes["node:input"].x,178); assert.equal(a.resolved_layout.boxes["node:queue"].x,330); assert.equal(a.resolved_layout.boxes["node:output"].x,502); });
test("LayoutIntent stays geometry-free while ResolvedLayout owns boxes and paths", () => { const result=compilePromotedLayout(promote(),request),intentText=JSON.stringify(result.layout_intent); assert.equal(/\"(?:x|y|w|h|path_d)\"\s*:/.test(intentText),false); assert.ok(result.layout_intent.intrinsic_metrics_hash.startsWith("sha256:")); assert.ok(result.resolved_layout.boxes["node:input"].anchors.east); assert.match(result.resolved_layout.connectors["relation:input-queue"].path_d,/^M/); });
test("relations route from deterministic east/west anchors on a horizontal grammar", () => { const route=compilePromotedLayout(promote(),request).resolved_layout.connectors["relation:input-queue"]; assert.equal(route.source_anchor,"node:input.east"); assert.equal(route.target_anchor,"node:queue.west"); assert.equal(route.obstacle_hits,0); });
test("minimum intrinsic sizes hard-fail instead of shrinking below the floor", () => { const tiny=structuredClone(request); tiny.target.viewport.width=320; const result=compilePromotedLayout(promote(),tiny); assert.equal(result.status,"fail"); assert.equal(result.resolved_layout,undefined); assert.ok(has(result,"LAY001_UNSAT")); });
test("soft gaps and preferred sizes shrink deterministically before hard failure", () => { const tight=structuredClone(request); tight.target.viewport.width=400; const result=compilePromotedLayout(promote(),tight),boxes=result.resolved_layout.boxes; assert.equal(result.status,"pass"); assert.ok(boxes["node:input"].w>=100); assert.ok(boxes["node:queue"].w>=100); assert.ok(boxes["node:output"].w>=100); assert.equal(boxes["node:input"].x,20); assert.equal(Math.round((boxes["node:output"].x+boxes["node:output"].w)*1000)/1000,380); });
test("missing or duplicate intrinsic measurements fail the layout gate", () => { const missing=structuredClone(request); missing.measurements.pop(); assert.ok(has(compilePromotedLayout(promote(),missing),"LAY001_UNSAT","node:output")); const duplicate=structuredClone(request); duplicate.measurements.push(structuredClone(duplicate.measurements[0])); assert.ok(has(compilePromotedLayout(promote(),duplicate),"LAY001_UNSAT","node:input")); });
test("layout request schema rejects unknown properties and target profile drift", () => { const unknown=structuredClone(request); unknown.extra=true; assert.ok(compilePromotedLayout(promote(),unknown).issues.some((entry)=>entry.code==="LAY001_UNSAT"&&entry.path==="$.extra")); const mismatch=structuredClone(request); mismatch.target.profile="paper"; assert.ok(has(compilePromotedLayout(promote(),mismatch),"LAY008_TARGET_MISSING")); });
test("measurement array order is non-authoritative", () => { const promotion=promote(),reversed=structuredClone(request); reversed.measurements.reverse(); const a=compilePromotedLayout(promotion,request),b=compilePromotedLayout(promotion,reversed); assert.equal(a.layout_intent.intrinsic_metrics_hash,b.layout_intent.intrinsic_metrics_hash); assert.equal(a.layout_hash,b.layout_hash); });
test("measurement semantics change intrinsic metrics identity", () => { const promotion=promote(),changed=structuredClone(request); changed.measurements[0].pref_w+=10; const a=compilePromotedLayout(promotion,request),b=compilePromotedLayout(promotion,changed); assert.notEqual(a.layout_intent.intrinsic_metrics_hash,b.layout_intent.intrinsic_metrics_hash); });
test("top-down grammar uses vertical placement and north/south ports", () => { const verticalFigure=structuredClone(figure); verticalFigure.composition.grammar.reading_axis="top-down"; const verticalRequest=structuredClone(request); verticalRequest.target.viewport={width:300,height:800}; const result=compilePromotedLayout(promote(verticalFigure),verticalRequest); assert.equal(result.status,"pass"); assert.ok(result.resolved_layout.boxes["node:input"].y<result.resolved_layout.boxes["node:queue"].y); const route=result.resolved_layout.connectors["relation:input-queue"]; assert.equal(route.source_anchor,"node:input.south"); assert.equal(route.target_anchor,"node:queue.north"); });
test("unsupported radial topology fails closed instead of falling back to stochastic layout", () => { const radialFigure=structuredClone(figure); radialFigure.composition.grammar.reading_axis="radial"; const result=compilePromotedLayout(promote(radialFigure),request); assert.equal(result.status,"fail"); assert.ok(has(result,"LAY009_RADIAL_TOPOLOGY")); });
test("raw or tampered promotion input is rejected before LayoutIntent", () => { assert.equal(compilePromotedLayout({promoted:false},request).status,"fail"); const tampered=promote(); tampered.promotion_receipt={...tampered.promotion_receipt,input_hash:"sha256:"+"0".repeat(64)}; const result=compilePromotedLayout(tampered,request); assert.equal(result.status,"fail"); assert.equal(result.layout_intent,undefined); });
test("gate promotion freezes ResolvedLayout and emits stable receipt", () => { const promotion=promote(),a=promoteResolvedLayout(promotion,request),b=promoteResolvedLayout(promotion,request); assert.equal(a.promoted,true); assert.equal(a.promotion_receipt.promotion_hash,b.promotion_receipt.promotion_hash); assert.equal(Object.isFrozen(a.resolved_layout),true); assert.equal(Object.isFrozen(a.resolved_layout.boxes),true); assert.equal(Object.isFrozen(a.promotion_receipt),true); });
test("root mirrors stay byte-identical to installable D-002 contracts", async () => { const pairs=[["../schemas/layout-request.schema.json","../skills/figthread/schemas/layout-request.schema.json"],["../schemas/layout-intent.schema.json","../skills/figthread/schemas/layout-intent.schema.json"],["../schemas/resolved-layout.schema.json","../skills/figthread/schemas/resolved-layout.schema.json"],["../examples/minimal.layout-request.json","../skills/figthread/examples/minimal.layout-request.json"]]; for(const [rootPath,skillPath] of pairs){const [root,skill]=await Promise.all([readFile(new URL(rootPath,import.meta.url),"utf8"),readFile(new URL(skillPath,import.meta.url),"utf8")]); assert.equal(root,skill);} });
