import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { promoteFigureSpec } from "../skills/figthread/runtime/validator.js";
import { promoteResolvedLayout } from "../skills/figthread/runtime/layout.js";
import { compilePromotedMotion, promoteMotionProgram, evaluateMotionProgram, getStaticMotionState } from "../skills/figthread/runtime/motion.js";

const figure = JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.figure.json", import.meta.url), "utf8"));
const request = JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.layout-request.json", import.meta.url), "utf8"));
const motion = JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.motion.json", import.meta.url), "utf8"));
function upstream(doc=figure, req=request){ const semantic=promoteFigureSpec(doc); assert.equal(semantic.promoted,true); const layout=promoteResolvedLayout(semantic,req); assert.equal(layout.promoted,true); return {semantic,layout}; }
const has=(report,code)=>report.issues.some(entry=>entry.code===code);

test("motion compiler consumes matching promoted semantic and layout artifacts",()=>{ const {semantic,layout}=upstream(); const a=compilePromotedMotion(semantic,layout,motion),b=compilePromotedMotion(semantic,layout,motion); assert.equal(a.status,"pass"); assert.equal(a.promotion_eligible,true); assert.equal(a.program_hash,b.program_hash); assert.deepEqual(a.motion_program,b.motion_program); });
test("raw or mismatched upstream artifacts fail before MotionProgram",()=>{ const {semantic,layout}=upstream(); assert.ok(has(compilePromotedMotion({promoted:false},layout,motion),"MOT001_BIND")); const other=structuredClone(figure); other.id="fig:other"; const otherSemantic=promoteFigureSpec(other); assert.equal(otherSemantic.promoted,true); assert.ok(has(compilePromotedMotion(otherSemantic,layout,{...motion,figure_id:"fig:other"}),"MOT001_BIND")); });
test("seeking is event-sourced and independent of previous samples",()=>{ const {semantic,layout}=upstream(),program=compilePromotedMotion(semantic,layout,motion).motion_program; const late=evaluateMotionProgram(program,2000),earlyAfter=evaluateMotionProgram(program,200),earlyFresh=evaluateMotionProgram(program,200); assert.equal(late.state["state:queue-count"],1); assert.deepEqual(earlyAfter,earlyFresh); assert.equal(earlyAfter.state["state:queue-count"],0); });
test("repeat timelines close and wrap to the initial semantic state",()=>{ const {semantic,layout}=upstream(),program=compilePromotedMotion(semantic,layout,motion).motion_program; assert.equal(evaluateMotionProgram(program,3500).state["state:queue-count"],0); assert.deepEqual(evaluateMotionProgram(program,3600).state,program.initial_state); assert.deepEqual(evaluateMotionProgram(program,7200).state,program.initial_state); });
test("transfer and trace cues resolve geometry only in MotionProgram",()=>{ const {semantic,layout}=upstream(),result=compilePromotedMotion(semantic,layout,motion),text=JSON.stringify(motion); assert.equal(/\"(?:x|y|path_d|points)\"\s*:/.test(text),false); const transfer=result.motion_program.tracks.find(track=>track.event_id==="event:transfer").cues[0]; assert.match(transfer.path_d,/^M/); assert.ok(Number.isFinite(transfer.start.x)); assert.ok(Number.isFinite(transfer.end.x)); const trace=result.motion_program.tracks.find(track=>track.event_id==="event:transfer").cues[1]; assert.equal(trace.path_d,layout.resolved_layout.connectors["relation:queue-output"].path_d); });
test("motion geometry nested anywhere in canonical spec is rejected",()=>{ const {semantic,layout}=upstream(),bad=structuredClone(motion); bad.extensions["vendor:test"]={frames:[{x:10}]}; const result=compilePromotedMotion(semantic,layout,bad); assert.ok(has(result,"MOT004_GEOMETRY")); assert.ok(has(result,"MOT009_PURITY")); });
test("state effects enforce operation and state-domain semantics",()=>{ const {semantic,layout}=upstream(),bad=structuredClone(motion); bad.events[0].effects[0]={state_id:"state:queue-count",op:"add",value:9}; const result=compilePromotedMotion(semantic,layout,bad); assert.ok(has(result,"MOT003_DOMAIN")); const booleanFigure=structuredClone(figure); booleanFigure.states[0].domain={type:"boolean"}; booleanFigure.states[0].initial=false; booleanFigure.states[0].summary=true; booleanFigure.snapshots[0].state_values["state:queue-count"]=true; const booleanMotion=structuredClone(motion); booleanMotion.events[0].effects[0]={state_id:"state:queue-count",op:"add",value:1}; booleanMotion.events[2].effects[0]={state_id:"state:queue-count",op:"set",value:false}; const u=upstream(booleanFigure); assert.ok(has(compilePromotedMotion(u.semantic,u.layout,booleanMotion),"MOT003_DOMAIN")); });
test("concurrent writes to one state at one semantic time are rejected",()=>{ const {semantic,layout}=upstream(),bad=structuredClone(motion); bad.events.push({id:"event:also-write",kind:"state-change",effects:[{state_id:"state:queue-count",op:"set",value:2}]}); bad.timeline.beats[0].event_ids.push("event:also-write"); assert.ok(has(compilePromotedMotion(semantic,layout,bad),"MOT006_WRITER")); });
test("cue references and cue windows are validated",()=>{ const {semantic,layout}=upstream(),badRef=structuredClone(motion); badRef.events[1].cues[0].via_relation="relation:missing"; assert.ok(has(compilePromotedMotion(semantic,layout,badRef),"MOT005_CUE")); const badTime=structuredClone(motion); badTime.events[0].cues[0].duration_ms=900; assert.ok(has(compilePromotedMotion(semantic,layout,badTime),"MOT002_TIME")); });
test("repeat loop requires explicit semantic closure",()=>{ const {semantic,layout}=upstream(),bad=structuredClone(motion); bad.events[2].effects=[]; assert.ok(has(compilePromotedMotion(semantic,layout,bad),"MOT007_LOOP")); const wrongMode=structuredClone(motion); wrongMode.timeline.loop={mode:"none",closure:"explicit-reset"}; assert.ok(has(compilePromotedMotion(semantic,layout,wrongMode),"MOT007_LOOP")); });
test("static motion state comes from the figure static summary snapshot",()=>{ const {semantic,layout}=upstream(),program=compilePromotedMotion(semantic,layout,motion).motion_program,staticState=getStaticMotionState(program); assert.equal(staticState.snapshot_id,figure.static_snapshot_id); assert.equal(staticState.state["state:queue-count"],1); assert.deepEqual(staticState.active_cues,[]); const bad=structuredClone(motion); bad.static_snapshot_id="snapshot:other"; assert.ok(has(compilePromotedMotion(semantic,layout,bad),"MOT008_STATIC")); });
test("unregistered canonical extensions fail purity validation",()=>{ const {semantic,layout}=upstream(),bad=structuredClone(motion); bad.extensions["acme:custom"]={mode:"custom"}; assert.ok(has(compilePromotedMotion(semantic,layout,bad),"MOT009_PURITY")); });
test("gate promotion freezes MotionProgram and emits a stable receipt",()=>{ const {semantic,layout}=upstream(),a=promoteMotionProgram(semantic,layout,motion),b=promoteMotionProgram(semantic,layout,motion); assert.equal(a.promoted,true); assert.equal(a.promotion_receipt.promotion_hash,b.promotion_receipt.promotion_hash); assert.equal(Object.isFrozen(a.motion_program),true); assert.equal(Object.isFrozen(a.motion_program.tracks),true); assert.equal(Object.isFrozen(a.promotion_receipt),true); });
test("draft mode remains non-authoritative",()=>{ const {semantic,layout}=upstream(),result=compilePromotedMotion(semantic,layout,motion,{mode:"draft"}); assert.equal(result.status,"pass"); assert.equal(result.promotion_eligible,false); });
test("root mirrors stay byte-identical to installable motion contracts",async()=>{ const pairs=[["../schemas/motion-spec.schema.json","../skills/figthread/schemas/motion-spec.schema.json"],["../examples/minimal.motion.json","../skills/figthread/examples/minimal.motion.json"]]; for(const [rootPath,skillPath] of pairs){const [root,skill]=await Promise.all([readFile(new URL(rootPath,import.meta.url),"utf8"),readFile(new URL(skillPath,import.meta.url),"utf8")]); assert.equal(root,skill);} });
