import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { sha256Canonical } from "../skills/figthread/runtime/canonicalize.js";
import { promoteFigureSpec } from "../skills/figthread/runtime/validator.js";
import { promoteGrammarPlan } from "../skills/figthread/runtime/grammar.js";
import { promoteVisualSpec } from "../skills/figthread/runtime/visual.js";
import { promoteProfilePlan } from "../skills/figthread/runtime/profile.js";
import { promoteProfileLayout } from "../skills/figthread/runtime/visual-layout.js";
import { promoteRenderedSvg } from "../skills/figthread/runtime/renderer.js";
import { compileVisualAuditEvidence, compileVisualAuditPlan, promoteVisualAuditEvidence, scanCustomSvg } from "../skills/figthread/runtime/visual-audit.js";

const figure=JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.figure.json",import.meta.url),"utf8"));
const visual=JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.visual.json",import.meta.url),"utf8"));
const auditVisual=JSON.parse(await readFile(new URL("../skills/figthread/examples/visual-audit-custom.visual.json",import.meta.url),"utf8"));
const target=JSON.parse(await readFile(new URL("../skills/figthread/examples/minimal.layout-target.json",import.meta.url),"utf8"));

function chain(visualDoc=visual){const fig=promoteFigureSpec(figure);assert.equal(fig.promoted,true);const grammar=promoteGrammarPlan(fig);assert.equal(grammar.promoted,true);const vis=promoteVisualSpec(fig,visualDoc);assert.equal(vis.promoted,true);const profile=promoteProfilePlan(fig,vis,target);assert.equal(profile.promoted,true);const layout=promoteProfileLayout(fig,grammar,vis,profile);assert.equal(layout.promoted,true);const render=promoteRenderedSvg(fig,vis,profile,layout);assert.equal(render.promoted,true);return{fig,vis,layout,render};}
function makeObservation(plan){const elements=plan.elements.map((entry)=>{if(entry.role==="text"){const b=entry.owner_box;return{element_id:entry.element_id,owner_id:entry.owner_id,source:entry.source,tag:entry.tag,role:entry.role,bbox:{x:b.x+6,y:b.y+6,w:20,h:10},visible:true,display:"block",visibility:"visible",opacity:1,stroke_width_px:0,points:[],text:"x",font_size_px:16,font_family:"sans-serif",font_weight:"400",font_available:true,platform_fonts:[{family_name:"Test Sans",glyph_count:1,is_custom_font:false}]};}return{element_id:entry.element_id,owner_id:entry.owner_id,source:entry.source,tag:entry.tag,role:entry.role,bbox:entry.owner_box?{x:entry.owner_box.x+4,y:entry.owner_box.y+4,w:8,h:8}:{x:2,y:2,w:20,h:1},visible:true,display:"block",visibility:"visible",opacity:1,stroke_width_px:1,points:entry.role==="connector"?[{x:2,y:2},{x:4,y:2},{x:6,y:2},{x:8,y:2},{x:10,y:2},{x:12,y:2}]:[]};}).sort((a,b)=>a.element_id.localeCompare(b.element_id));const base={schema_version:"figthread.visual-audit-observation/0.1",plan_hash:plan.plan_hash,figure_hash:plan.figure_hash,visual_hash:plan.visual_hash,layout_hash:plan.layout_hash,render_hash:plan.render_hash,svg_hash:plan.svg_hash,target_id:plan.target_id,viewport:plan.viewport,elements,environment:{browser_product:"Chrome/1",browser_revision:"r1",protocol_version:"1",user_agent:"test",platform:"test",device_pixel_ratio:1}};return{...base,observation_hash:sha256Canonical(base)};}
const rehash=(observation)=>{const copy=structuredClone(observation);delete copy.observation_hash;copy.observation_hash=sha256Canonical(copy);return copy;};

test("custom SVG scanner covers text and classified visible geometry",()=>{const scanned=scanCustomSvg('<g><rect data-figthread-audit="container"/><path data-essential="true"/><text>label</text><line data-figthread-audit="connector"/><defs><path/></defs></g>');assert.deepEqual(scanned.elements.map((entry)=>[entry.tag,entry.role]),[["rect","container"],["path","essential"],["text","text"],["line","connector"]]);assert.deepEqual(scanned.unsupported,[]);});

test("visual audit plan binds every rendered primary label and relation",()=>{const c=chain(),result=compileVisualAuditPlan(c.fig,c.vis,c.layout,c.render);assert.equal(result.status,"pass");assert.equal(result.visual_audit_plan.elements.filter((entry)=>entry.source==="semantic-label").length,figure.nodes.length);assert.equal(result.visual_audit_plan.elements.filter((entry)=>entry.source==="relation").length,figure.relations.length);assert.match(result.plan_hash,/^sha256:[0-9a-f]{64}$/);});

test("classified custom fixture promotes into complete custom audit scope",()=>{const c=chain(auditVisual),result=compileVisualAuditPlan(c.fig,c.vis,c.layout,c.render);assert.equal(result.status,"pass",JSON.stringify(result.issues));const custom=result.visual_audit_plan.elements.filter((entry)=>entry.source==="custom");assert.deepEqual(custom.map((entry)=>entry.role).sort(),["container","decorative","essential","text"]);assert.equal(custom.every((entry)=>entry.owner_id==="node:input"),true);});

test("unclassified custom geometry fails coverage before browser capture",()=>{const custom=structuredClone(visual);custom.custom_definitions.push({id:"custom.audit-probe@0.1",class:"mechanism",renderer:"svg",variants:["main"],view_box:[0,0,120,80],intrinsic:{min_w:100,min_h:60,pref_w:120,pref_h:80,aspect_policy:"free"},ports:["north","east","south","west"],slots:[],state_channels:[],tokens:["ink"],local_svg:'<g><rect x="2" y="2" width="116" height="76" fill="none" stroke="#1f2328" stroke-width="2" data-essential="true"/><circle cx="30" cy="30" r="8" fill="none" stroke="#1f2328" stroke-width="2"/></g>'});custom.bindings[1]={...custom.bindings[1],primitive:"custom.audit-probe@0.1",variant:"main",state_bindings:{}};const c=chain(custom),result=compileVisualAuditPlan(c.fig,c.vis,c.layout,c.render);assert.equal(result.status,"fail");assert.ok(result.issues.some((entry)=>entry.code==="AUD003_COVERAGE"&&entry.element_id?.startsWith("custom:node:input:")));});

test("content-hashed observation promotes when coverage, bounds, fonts, and clearances pass",()=>{const c=chain(),plan=compileVisualAuditPlan(c.fig,c.vis,c.layout,c.render).visual_audit_plan,observation=makeObservation(plan),result=promoteVisualAuditEvidence(c.fig,c.vis,c.layout,c.render,observation);assert.equal(result.promoted,true,JSON.stringify(result.report.issues));assert.equal(result.visual_audit_evidence.metrics.full_text_coverage_certified,true);assert.equal(result.visual_audit_evidence.metrics.connector_clearance_certified,true);assert.equal(Object.isFrozen(result.visual_audit_evidence),true);});

test("text collision and connector clearance failures are fail-closed",()=>{const c=chain(),plan=compileVisualAuditPlan(c.fig,c.vis,c.layout,c.render).visual_audit_plan;let observation=makeObservation(plan);const texts=observation.elements.filter((entry)=>entry.role==="text");texts[1].bbox={...texts[0].bbox};observation=rehash(observation);let result=compileVisualAuditEvidence(c.fig,c.vis,c.layout,c.render,observation);assert.equal(result.status,"fail");assert.ok(result.issues.some((entry)=>entry.code==="AUD005_TEXT_COLLISION"));observation=makeObservation(plan);const connector=observation.elements.find((entry)=>entry.role==="connector"),text=observation.elements.find((entry)=>entry.role==="text");connector.points=Array.from({length:8},()=>({x:text.bbox.x+2,y:text.bbox.y+2}));observation=rehash(observation);result=compileVisualAuditEvidence(c.fig,c.vis,c.layout,c.render,observation);assert.equal(result.status,"fail");assert.ok(result.issues.some((entry)=>entry.code==="AUD007_CONNECTOR_CLEARANCE"));});

test("tampered visual audit observation hash is rejected",()=>{const c=chain(),plan=compileVisualAuditPlan(c.fig,c.vis,c.layout,c.render).visual_audit_plan,observation=makeObservation(plan);observation.elements[0].bbox.x+=1;const result=compileVisualAuditEvidence(c.fig,c.vis,c.layout,c.render,observation);assert.equal(result.status,"fail");assert.ok(result.issues.some((entry)=>entry.code==="AUD010_EVIDENCE"));});
