import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { sha256Canonical } from "./canonicalize.js";

export const GRAMMAR_ENGINE_VERSION = "0.1.0";
export const GRAMMAR_PLAN_SCHEMA_VERSION = "figthread.grammar-plan/0.1";
const REGISTRY = JSON.parse(readFileSync(fileURLToPath(new URL("../grammars/registry.json", import.meta.url)), "utf8"));
const severityOrder = { error: 0, warning: 1, note: 2 };
const issue = (code, severity, message, extra = {}) => ({ code, severity, stage_owner: "grammar", message, ...extra });
const sortIssues = (issues) => issues.sort((a,b)=>severityOrder[a.severity]-severityOrder[b.severity]||a.code.localeCompare(b.code)||(a.object_id??"").localeCompare(b.object_id??"")||(a.path??"").localeCompare(b.path??"")||a.message.localeCompare(b.message));
function deepFreeze(value, seen=new Set()){ if(value===null||typeof value!=="object"||seen.has(value))return value; seen.add(value); for(const child of Object.values(value))deepFreeze(child,seen); return Object.freeze(value); }
function readFigurePromotion(p){ if(!p?.promoted||!p.validated_figure||!p.promotion_receipt)return null; const {promotion_hash,...base}=p.promotion_receipt; if(sha256Canonical(base)!==promotion_hash)return null; if(sha256Canonical(p.validated_figure)!==p.promotion_receipt.input_hash)return null; return {figure:p.validated_figure,figureHash:p.promotion_receipt.input_hash}; }
const axis=(v)=>["left-right","horizontal","x"].includes(v)?"x":["top-down","vertical","y"].includes(v)?"y":["radial","clockwise"].includes(v)?"radial":null;
const role=(g,n)=>Array.isArray(g?.role_bindings?.[n])?g.role_bindings[n]:[];
const defFor=(id)=>REGISTRY.definitions.find((d)=>d.id===id)??null;
function duplicates(values){const seen=new Set(),out=new Set(); for(const v of values)seen.has(v)?out.add(v):seen.add(v); return [...out].sort();}
function edgeMap(ids,rels){const set=new Set(ids),out=new Map(ids.map(id=>[id,[]])),incoming=new Map(ids.map(id=>[id,[]])); for(const r of rels)if(set.has(r.from)&&set.has(r.to)){out.get(r.from).push(r.to);incoming.get(r.to).push(r.from);} return {out,incoming};}
function hasCycle(ids,rels){const {out}=edgeMap(ids,rels),state=new Map(ids.map(id=>[id,0])); function visit(id){if(state.get(id)===1)return true;if(state.get(id)===2)return false;state.set(id,1);for(const n of out.get(id)??[])if(visit(n))return true;state.set(id,2);return false;}return [...ids].sort().some(visit);}
function weaklyConnected(ids,rels){if(ids.length<=1)return true;const set=new Set(ids),adj=new Map(ids.map(id=>[id,new Set()]));for(const r of rels)if(set.has(r.from)&&set.has(r.to)){adj.get(r.from).add(r.to);adj.get(r.to).add(r.from);}const seen=new Set(),q=[ids[0]];while(q.length){const id=q.shift();if(seen.has(id))continue;seen.add(id);for(const n of [...adj.get(id)].sort())if(!seen.has(n))q.push(n);}return seen.size===ids.length;}
const direct=(rels,a,b)=>rels.some(r=>r.from===a&&r.to===b);
const primaryRole=(type)=>({comparison:"subjects",architecture:"components",pipeline:"stages",mechanism:"components","state-transition":"states",timeline:"events",network:"nodes",hierarchy:"members",swimlane:"steps",lifecycle:"phases",dataflow:"operators","multi-panel":"panels"})[type];
function allRoleIds(g,d){const names=[...Object.keys(d.required_roles??{}),...(d.optional_roles??[])];return [...new Set(names.flatMap(n=>role(g,n)))].sort();}
function validateRoles(fig,d,v,issues){const g=fig.composition.grammar,b=g.role_bindings??{},nodeIds=new Set(fig.nodes.map(n=>n.id)),allowed=new Set([...Object.keys(d.required_roles??{}),...(d.optional_roles??[])]);for(const n of Object.keys(b).sort())if(!allowed.has(n))issues.push(issue("GRM002_ROLE","error",`grammar role ${n} is not declared by ${d.id}`,{path:`$.composition.grammar.role_bindings.${n}`}));for(const [n,bounds] of Object.entries(d.required_roles??{})){const values=b[n];if(!Array.isArray(values)){issues.push(issue("GRM002_ROLE","error",`required role ${n} must be an array`,{path:`$.composition.grammar.role_bindings.${n}`}));continue;}if(values.length<bounds.min||values.length>bounds.max)issues.push(issue("GRM004_CARDINALITY","error",`${n} requires ${bounds.min}–${bounds.max} nodes, received ${values.length}`,{path:`$.composition.grammar.role_bindings.${n}`}));}for(const n of d.optional_roles??[])if(b[n]!==undefined&&!Array.isArray(b[n]))issues.push(issue("GRM002_ROLE","error",`optional role ${n} must be an array`,{path:`$.composition.grammar.role_bindings.${n}`}));for(const n of allowed){for(const dup of duplicates(role(g,n)))issues.push(issue("GRM002_ROLE","error",`role ${n} repeats ${dup}`,{object_id:dup}));for(const id of role(g,n))if(!nodeIds.has(id))issues.push(issue("GRM002_ROLE","error",`role ${n} references unknown node ${id}`,{object_id:id}));}for(const n of v.requires_roles??[])if(!role(g,n).length)issues.push(issue("GRM007_VARIANT","error",`variant ${g.variant} requires role ${n}`,{path:`$.composition.grammar.role_bindings.${n}`}));}
function validateOrder(fig,d,issues){const order=fig.composition.order;for(const dup of duplicates(order))issues.push(issue("GRM005_ORDER","error",`composition order repeats ${dup}`,{object_id:dup}));const name=primaryRole(d.id),ids=role(fig.composition.grammar,name),index=new Map(order.map((id,i)=>[id,i]));for(const id of ids)if(!index.has(id))issues.push(issue("GRM005_ORDER","error",`${name} contains ${id}, which is absent from composition order`,{object_id:id}));const projected=ids.filter(id=>index.has(id)).sort((a,b)=>index.get(a)-index.get(b));if(projected.length===ids.length&&projected.some((id,i)=>id!==ids[i]))issues.push(issue("GRM005_ORDER","error",`${name} order contradicts composition reading order`));}
function allowedRelations(fig,d,ids,issues){const allowed=new Set(d.topology.allowed_relations??[]),bound=new Set(ids),relevant=fig.relations.filter(r=>bound.has(r.from)&&bound.has(r.to)),good=relevant.filter(r=>allowed.has(r.kind)),foreign=relevant.filter(r=>!allowed.has(r.kind));if(foreign.length){const ratio=foreign.length/Math.max(1,relevant.length);issues.push(issue(ratio>0.2?"GRM010_HYBRID":"GRM003_RELATION",ratio>0.2?"error":"warning",`${foreign.length}/${relevant.length} grammar-internal relation(s) fall outside ${d.id} vocabulary`,{object_id:foreign.sort((a,b)=>a.id.localeCompare(b.id))[0].id}));}return good;}
function nearestPanel(id,nodeById,root,panelSet){let n=nodeById.get(id),seen=new Set();while(n&&!seen.has(n.id)){seen.add(n.id);if(panelSet.has(n.id))return n.id;if(!n.parent_id||n.parent_id===root)return null;n=nodeById.get(n.parent_id);}return null;}
function specifics(fig,d,v,rels,issues){const g=fig.composition.grammar,b=g.role_bindings,nodeById=new Map(fig.nodes.map(n=>[n.id,n]));if(d.id==="pipeline"){const ids=role(g,"stages"),{out,incoming}=edgeMap(ids,rels);if(!weaklyConnected(ids,rels))issues.push(issue("GRM003_RELATION","error","pipeline stages must form one connected flow"));for(const id of ids){if((out.get(id)?.length??0)>(v.max_out??Infinity))issues.push(issue("GRM004_CARDINALITY","error",`${id} exceeds branch-out limit`,{object_id:id}));if((incoming.get(id)?.length??0)>(v.max_in??Infinity))issues.push(issue("GRM004_CARDINALITY","error",`${id} exceeds merge-in limit`,{object_id:id}));}if(g.variant==="linear")for(let i=0;i+1<ids.length;i++)if(!direct(rels,ids[i],ids[i+1]))issues.push(issue("GRM003_RELATION","error",`linear pipeline requires direct flow ${ids[i]} → ${ids[i+1]}`,{object_id:ids[i]}));}
if(d.id==="mechanism"){const ids=role(g,"components");if(!rels.length)issues.push(issue("GRM003_RELATION","error","mechanism requires a causal relation among components"));if(g.variant==="feedback-loop"&&!hasCycle(ids,rels))issues.push(issue("GRM006_CYCLE","error","feedback-loop mechanism requires a causal cycle"));}
if(d.id==="state-transition"){const ids=role(g,"states");for(const id of ids)if(nodeById.get(id)?.kind!=="state")issues.push(issue("GRM002_ROLE","error",`${id} must be a semantic state node`,{object_id:id}));if(!rels.length)issues.push(issue("GRM003_RELATION","error","state-transition requires at least one trigger transition"));}
if(d.id==="network"){const ids=role(g,"nodes"),degree=new Map(ids.map(id=>[id,0]));for(const r of rels){degree.set(r.from,(degree.get(r.from)??0)+1);degree.set(r.to,(degree.get(r.to)??0)+1);}for(const [id,n] of degree)if(!n)issues.push(issue("GRM003_RELATION","error",`network node ${id} is isolated`,{object_id:id}));if(g.variant==="radial"&&role(g,"hub").length!==1)issues.push(issue("GRM004_CARDINALITY","error","radial network requires exactly one hub"));}
if(d.id==="hierarchy"){const roots=role(g,"root"),members=role(g,"members"),rootId=roots[0],ids=[...new Set([...roots,...members])],{incoming}=edgeMap(ids,rels);if(rootId&&(incoming.get(rootId)?.length??0)!==0)issues.push(issue("GRM003_RELATION","error",`hierarchy root ${rootId} must not have a parent edge`,{object_id:rootId}));for(const id of members)if(id!==rootId&&(incoming.get(id)?.length??0)!==1)issues.push(issue("GRM003_RELATION","error",`hierarchy member ${id} must have exactly one parent edge`,{object_id:id}));if(!weaklyConnected(ids,rels))issues.push(issue("GRM003_RELATION","error","hierarchy must form one connected structure"));}
if(d.id==="swimlane"){const lanes=new Set(role(g,"lanes")),steps=role(g,"steps"),stepSet=new Set(steps);for(const id of steps)if(!lanes.has(nodeById.get(id)?.data?.lane_id))issues.push(issue("GRM008_COMPOSITION","error",`swimlane step ${id} must declare data.lane_id referencing a bound lane`,{object_id:id}));if(!weaklyConnected(steps,rels.filter(r=>stepSet.has(r.from)&&stepSet.has(r.to))))issues.push(issue("GRM003_RELATION","error","swimlane steps must form one connected process"));}
if(d.id==="lifecycle"){const ids=role(g,"phases");for(let i=0;i<ids.length;i++){const next=ids[(i+1)%ids.length];if(!direct(rels,ids[i],next))issues.push(issue("GRM006_CYCLE","error",`lifecycle requires explicit closure edge ${ids[i]} → ${next}`,{object_id:ids[i]}));}}
if(d.id==="dataflow"){const operators=role(g,"operators"),artifacts=role(g,"artifacts"),all=[...new Set([...operators,...artifacts,...role(g,"stores")])],degree=new Map(all.map(id=>[id,0]));for(const id of operators.filter(id=>artifacts.includes(id)).sort())issues.push(issue("GRM002_ROLE","error",`${id} cannot be both operator and artifact`,{object_id:id}));for(const r of rels){if(degree.has(r.from))degree.set(r.from,degree.get(r.from)+1);if(degree.has(r.to))degree.set(r.to,degree.get(r.to)+1);}for(const [id,n] of degree)if(!n)issues.push(issue("GRM003_RELATION","error",`dataflow node ${id} has no provenance relation`,{object_id:id}));}
if(d.id==="multi-panel"){const panels=role(g,"panels"),set=new Set(panels),root=fig.composition.root_id;for(const id of panels){const n=nodeById.get(id);if(n?.kind!=="panel"||n?.parent_id!==root)issues.push(issue("GRM008_COMPOSITION","error",`${id} must be a direct child panel of the composition root`,{object_id:id}));}for(const r of fig.relations){const a=nearestPanel(r.from,nodeById,root,set),b2=nearestPanel(r.to,nodeById,root,set);if(a&&b2&&a!==b2)issues.push(issue("GRM008_COMPOSITION","error",`cross-panel relation ${r.id} is forbidden`,{object_id:r.id}));}}
}
export const GRAMMAR_REGISTRY_HASH = REGISTRY.registry_hash;
if(sha256Canonical({schema_version:REGISTRY.schema_version,definitions:REGISTRY.definitions})!==GRAMMAR_REGISTRY_HASH)throw new Error("bundled grammar registry hash mismatch");
if(REGISTRY.definitions.length!==12||new Set(REGISTRY.definitions.map(d=>d.id)).size!==12)throw new Error("bundled grammar registry must contain twelve unique root grammars");
function compilePlan(fig,figureHash,d){const g=fig.composition.grammar,base={schema_version:GRAMMAR_PLAN_SCHEMA_VERSION,figure_hash:figureHash,registry_hash:GRAMMAR_REGISTRY_HASH,definition_hash:sha256Canonical(d),grammar_id:d.id,variant:g.variant,primary_axis:axis(g.reading_axis),reading_order:g.type==="hierarchy"?[...role(g,"root"),...role(g,"members")]:fig.composition.order.slice(),role_bindings:structuredClone(g.role_bindings),topology:structuredClone(d.topology),split:structuredClone(d.split),layout:structuredClone(d.layout),engine_version:GRAMMAR_ENGINE_VERSION};return deepFreeze({...base,plan_hash:sha256Canonical(base)});}
export function validateGrammar(figurePromotion,options={}){const mode=options.mode??"gate";if(!["draft","gate"].includes(mode))throw new TypeError("grammar mode must be 'draft' or 'gate'");const promoted=readFigurePromotion(figurePromotion);if(!promoted)return{mode,status:"fail",promotion_eligible:false,grammar_engine_version:GRAMMAR_ENGINE_VERSION,registry_hash:GRAMMAR_REGISTRY_HASH,issues:[issue("GRM001_TYPE","error","grammar validation requires a valid promoted semantic figure",{stage_owner:"semantic"})]};const fig=promoted.figure,g=fig.composition?.grammar,d=defFor(fig.figure_type),issues=[];if(!d)issues.push(issue("GRM001_TYPE","error",`unknown figure grammar ${fig.figure_type}`));if(!g||g.type!==fig.figure_type)issues.push(issue("GRM001_TYPE","error",`composition grammar type must match figure_type ${fig.figure_type}`));if(!d||!g||g.type!==fig.figure_type)return{figure_hash:promoted.figureHash,mode,status:"fail",promotion_eligible:false,grammar_engine_version:GRAMMAR_ENGINE_VERSION,registry_hash:GRAMMAR_REGISTRY_HASH,issues:sortIssues(issues)};const v=d.variants[g.variant];if(!v)issues.push(issue("GRM007_VARIANT","error",`${d.id} does not define variant ${g.variant}`));if(!axis(g.reading_axis))issues.push(issue("GRM005_ORDER","error",`unsupported reading axis ${g.reading_axis}`));if(v&&!v.axes.includes(g.reading_axis))issues.push(issue("GRM007_VARIANT","error",`${g.variant} does not allow reading axis ${g.reading_axis}`));if(v)validateRoles(fig,d,v,issues);validateOrder(fig,d,issues);const ids=allRoleIds(g,d),rels=allowedRelations(fig,d,ids,issues);if(d.topology.cycle_policy==="forbid"&&hasCycle(ids,rels))issues.push(issue("GRM006_CYCLE","error",`${d.id} forbids semantic cycles`));if(d.topology.cycle_policy==="require"&&!hasCycle(ids,rels))issues.push(issue("GRM006_CYCLE","error",`${d.id} requires a semantic cycle`));if(v?.requires_cycle&&!hasCycle(ids,rels))issues.push(issue("GRM006_CYCLE","error",`${g.variant} requires a semantic cycle`));if(v)specifics(fig,d,v,rels,issues);const nodeCount=fig.nodes.filter(n=>n.id!==fig.composition.root_id).length;if(nodeCount>d.split.nodes_hard)issues.push(issue("GRM009_SPLIT","error",`${d.id} semantic node count ${nodeCount} exceeds split cap ${d.split.nodes_hard}`));if(fig.relations.length>d.split.relations_hard)issues.push(issue("GRM009_SPLIT","error",`${d.id} relation count ${fig.relations.length} exceeds split cap ${d.split.relations_hard}`));const sorted=sortIssues(issues),hasErrors=sorted.some(x=>x.severity==="error"),result={figure_hash:promoted.figureHash,registry_hash:GRAMMAR_REGISTRY_HASH,definition_hash:sha256Canonical(d),grammar_id:d.id,mode,status:hasErrors?"fail":sorted.some(x=>x.severity==="warning")?"pass-with-warnings":"pass",promotion_eligible:mode==="gate"&&!hasErrors,grammar_engine_version:GRAMMAR_ENGINE_VERSION,issues:sorted};if(!hasErrors){result.grammar_plan=compilePlan(fig,promoted.figureHash,d);result.grammar_plan_hash=result.grammar_plan.plan_hash;}return result;}
export function promoteGrammarPlan(figurePromotion){const result=validateGrammar(figurePromotion,{mode:"gate"});if(!result.promotion_eligible)return{promoted:false,report:result};const p=result.grammar_plan,base={kind:"grammar_plan",schema_version:GRAMMAR_PLAN_SCHEMA_VERSION,figure_hash:result.figure_hash,registry_hash:result.registry_hash,definition_hash:result.definition_hash,grammar_id:result.grammar_id,grammar_plan_hash:p.plan_hash,engine_version:GRAMMAR_ENGINE_VERSION};return{promoted:true,report:result,grammar_plan:p,promotion_receipt:deepFreeze({...base,promotion_hash:sha256Canonical(base)})};}
export function readGrammarPromotion(p){if(!p?.promoted||!p.grammar_plan||!p.promotion_receipt)return null;const {promotion_hash,...base}=p.promotion_receipt;if(sha256Canonical(base)!==promotion_hash)return null;const {plan_hash,...planBase}=p.grammar_plan;if(sha256Canonical(planBase)!==plan_hash||plan_hash!==p.promotion_receipt.grammar_plan_hash)return null;if(p.grammar_plan.figure_hash!==p.promotion_receipt.figure_hash||p.grammar_plan.registry_hash!==p.promotion_receipt.registry_hash||p.grammar_plan.definition_hash!==p.promotion_receipt.definition_hash)return null;return{plan:p.grammar_plan,figureHash:p.promotion_receipt.figure_hash,registryHash:p.promotion_receipt.registry_hash,definitionHash:p.promotion_receipt.definition_hash,grammarPlanHash:p.promotion_receipt.grammar_plan_hash,grammarId:p.promotion_receipt.grammar_id};}
